# 1. Files excluded from Jekyll builds
# 2. Plugins
# 3. Jekyll/Gem settings
# 4. Collections
# 5. Scholar

# 1. Files excluded from Jekyll builds
exclude:
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- ADA-theme.gemspec
- .jekyll-cache

# 2. Plugins
gems:
  - jekyll-email-protect

plugins:
  - 'jekyll/scholar'
  - 'jekyll-remote-theme'

# Load ADA theme
remote_theme: ADA-research/jekyll-theme-ada #@v1.0.2

# 3. Jekyll settings
paginate: 1
paginate_path: "/blog/page:num/"

author: Jakob Bossek
email: "bossek@aim.rwth-aachen.de"
encoding: utf-8
lang: en-GB
title: "Chair for Artificial Intelligence Methodology (AIM) at RWTH Aachen University" # site name or title
logo: /assets/images/logo/AIM_logo.png
logo_alt_text: "Logo of the Chair for AI Methodology (AIM) at RWTH Aachen University"
description: "The Chair for AI Methodology (AIM) at RWTH Aachen University is led by Alexander von Humboldt Professor Dr. Holger Hoos. The AIM group conducts research across different areas of AI, including machine learning, automated reasoning and optimisation." # site description / default description

defaults:
  - scope:
      path: ""
      type: "collaborators"
    values:
      layout: "collaborator"
  - scope:
      path: ""
    values:
      layout: "default"

# 4. Collections
collections:
  members:
    sort_by: order
  members_past:
    sort_by: order
  collaborators:
    sort_by: order
    output: true

# 5. Scholar
scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  #bibliography_list_tag: ul

  source: _bibliography
  # repository: pdf
  bibliography: bib
  bibliography_template: bibentry

  replace_strings: true

  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details

  query: "@*"
